for _ in range(int(input())):
    D,FM,BM,T,FBS,BBS=input().split()
    FM,BM,T,FBS,BBS=int(FM),int(BM),int(T),int(FBS),int(BBS)
    forwardCycle=0
    backwardCycle=0
    currentPosition=0
    time=0
    if(D=="F"):
        if(FBS>FM and FM-BM==0):
            print("Hurray")
            continue
        while(True):
            if(currentPosition+FM<FBS):
                currentPosition+=FM
                forwardCycle+=1
            else:
                totalDistance=(forwardCycle*FM)+(backwardCycle*BM)+(FBS-currentPosition)
                time=totalDistance*T
                print(time,"F")
                break
            if(currentPosition-BM>-BBS):
                currentPosition-=BM
                backwardCycle+=1
            else:
                totalDistance=forwardCycle*FM+backwardCycle*BM+(BBS+currentPosition)
                time=totalDistance*T
                print(time,"B")
                break
    else:
        if(BBS>BM and FM-BM==0):
                print("Hurray")
                continue
        while(True):
            if(currentPosition-BM>-BBS):
                currentPosition-=BM
                backwardCycle+=1
            else:
                totalDistance=forwardCycle*FM+backwardCycle*BM+(BBS+currentPosition)
                time=totalDistance*T
                print(time,"B")
                break
            if(currentPosition+FM<FBS):
                currentPosition+=FM
                forwardCycle+=1
            else:
                totalDistance=(forwardCycle*FM)+(backwardCycle*BM)+(FBS-currentPosition)
                time=totalDistance*T
                print(time,"F")
                break
